# mkdocs.yml

# -------------------------------------------------------------
# CONFIGURACIÓN GENERAL DEL SITIO
# -------------------------------------------------------------
site_name: PPS-Unidad1-Pruebas_de_APP's # Define el título que aparecerá en la barra de navegación y en la etiqueta <title> del navegador.

# -------------------------------------------------------------
# ESTRUCTURA DE NAVEGACIÓN (MENÚ)
# -------------------------------------------------------------
# Define la lista de enlaces y el orden de aparición en el menú de navegación principal.
nav:
  # El nombre de la sección en el menú: nombre_archivo.md
  - Inicio: index.md
  - Elementos de python: ElementosDePython.md
  - Ejecución y depuración: EjecucionYDepuracion.md
  - Pruebas: Pruebas.md
  - Ejecucion en Sandbox: EjecucionEnSandbox.md
  - Comparacion de lenguajes: ComparacionEstructuralDeLenguajesFamosos.md

# Se pueden añadir subsecciones anidando listas:
  # - Referencia: 
  #   - Funciones: referencia/funciones.md
  #   - Clases: referencia/clases.md

# -------------------------------------------------------------
# DIRECTORIOS
# -------------------------------------------------------------
# Ruta de la carpeta que contiene todos los archivos .md (Markdown) de la documentación.
# MkDocs buscará aquí los archivos listados en 'nav'.
docs_dir: docs 
# -------------------------------------------------------------
# TEMA (Opcional, pero común)
# -------------------------------------------------------------
theme:
  name: material
  features:
    - navigation.tabs          # pestañas horizontales
    - navigation.tabs.sticky   # pestañas fijas arriba
    - navigation.instant       # navegación sin recargar
    - toc.integrate            # índice integrado en el contenido
  palette:
    # Modo claro
    - scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro
    # Modo oscuro
    - scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro


